### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by jadeclan** [jadeclan/Sudoku-JB#2]
### To Do List
- [ ] Implement Game Logic
- [ ] Add back/cancel buttons to About & SettingsActivity activities.
- [ ] Implement saving and continuing a game

Thanks to https://github.com/raganwald for md code for this to do list
